version: "3.9"
services:
  # application:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   image: application
  #   container_name: application
  #   volumes:
  #     - ./:/app/
  #   networks:
  #     - net

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000
    networks:
      - net
    healthcheck:
      # Adjust below to match your container port
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  index_data:
    driver: local
  backups:
    driver: local

networks:
  net:
    driver: bridge
